### ISSUE TITLE
Exception on upload when running on Node 11.x

### ISSUE THREAD

**Issue by siman** [Joystream/storage-node-joystream#20]
```console
internal/streams/pipeline.js:61
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at popCallback (internal/streams/pipeline.js:61:11)
    at Function.pipeline (internal/streams/pipeline.js:66:20)
    at IncomingMessage.readableStream.once (/ ... /storage-node-joystream/node_modules/file-type/index.js:943:19)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:189:13)
    at emitReadable_ (_stream_readable.js:539:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by siman** [comment]
Depends on https://github.com/sindresorhus/file-type/issues/196

**Comment by siman** [comment]
temporary fix to `file-type` until the new version is out:
change at the end of this file: `node_modules/file-type/index.js`

FROM:
```js
resolve(stream.pipeline(readableStream, pass));
```

TO:
```js
resolve(stream.pipeline(readableStream, pass, () => {}));
```
