### ISSUE TITLE
Problem trying to download content

### ISSUE THREAD

**Issue by mnaamani** [Joystream/storage-node-joystream#35]
Experiencing problem downloading from storage node. We get around 4K of the file then connection is dropped:

simple test with wget:
```
wget https://storage-node-1.joystream.org/asset/v0/d084fcd9-c489-57ff-9816-9917aaec0e1e/ef9818a5b76c-4989-b347-31128ebba?download 
--2019-04-14 17:15:53--  https://storage-node-1.joystream.org/asset/v0/d084fcd9-c489-57ff-9816-9917aaec0e1e/ef9818a5b76c-4989-b347-31128ebba?download
Resolving storage-node-1.joystream.org (storage-node-1.joystream.org)... 80.85.86.213
Connecting to storage-node-1.joystream.org (storage-node-1.joystream.org)|80.85.86.213|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 74063411 (71M) [application/octet-stream]
Saving to: 'ef9818a5b76c-4989-b347-31128ebba?download.3'

ef9818a5b76c-4989-b347-31128ebba?download   0%[                                                                                    ]   4.00K  --.-KB/s    in 0.03s   

2019-04-14 17:15:54 (149 KB/s) - Connection closed at byte 4096. Retrying.
```

Debug logs on storage node:

```bash
  joystream:repository Opening /ef9818a5b76c-4989-b347-31128ebba with mode r +1ms
  joystream:repository Initialized hyperdrive storage at: /home/joystream/STORAGE/repos/d0/84/d084fcd9-c489-57ff-9816-9917aaec0e1e +6ms
  joystream:repository Reading 4100 Bytes from the stream. +15ms
  joystream:repository Detected file type is application/octet-stream +3ms
  joystream:util:ranges RangeSender: RangeSender {
  name: 'ef9818a5b76c-4989-b347-31128ebba.bin',
  type: 'application/octet-stream',
  size: 74063411,
  ranges: undefined,
  download: true,
  read_offset: 0,
  range_index: -1,
  range_boundary: undefined,
  handlers: {},
  opened: false } +1ms
  joystream:util:ranges No ranges, just send the whole file. +1ms
  joystream:util:ranges Open succeeded: ef9818a5b76c-4989-b347-31128ebba.bin application/octet-stream +1ms
  joystream:util:ranges End of stream. +6ms
  joystream:util:ranges Error: Error: stream.push() after EOF
    at readableAddChunk (/home/joystream/storage-node-joystream/node_modules/readable-stream/lib/_stream_readable.js:271:30)
    at Class.Readable.push (/home/joystream/storage-node-joystream/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at check (/home/joystream/storage-node-joystream/node_modules/from2/index.js:60:16)
    at Request._callback (/home/joystream/storage-node-joystream/node_modules/hyperdrive/index.js:471:7)
    at Request.callback (/home/joystream/storage-node-joystream/node_modules/random-access-storage/index.js:161:8)
    at onread (/home/joystream/storage-node-joystream/node_modules/random-access-file/index.js:81:31)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:462:17) +4ms
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/home/joystream/storage-node-joystream/node_modules/express/lib/response.js:767:10)
    at ServerResponse.expressOpenAPISend [as send] (/home/joystream/storage-node-joystream/lib/joystream/middleware/validate_responses.js:34:13)
    at RangeSender.on_error (/home/joystream/storage-node-joystream/lib/joystream/util/ranges.js:171:43)
    at Class.emit (events.js:189:13)
    at readableAddChunk (/home/joystream/storage-node-joystream/node_modules/readable-stream/lib/_stream_readable.js:271:16)
    at Class.Readable.push (/home/joystream/storage-node-joystream/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at check (/home/joystream/storage-node-joystream/node_modules/from2/index.js:60:16)
    at Request._callback (/home/joystream/storage-node-joystream/node_modules/hyperdrive/index.js:471:7)
    at Request.callback (/home/joystream/storage-node-joystream/node_modules/random-access-storage/index.js:161:8)
```

**Comment by jfinkhaeuser** [comment]
The error makes sense, but not that this is the first time it happens. What node version?

**Comment by mnaamani** [comment]
Node:  v10.15.3
NPM: 6.4.1
yarn: 1.15.2

note: I'm running storage node  like so:

`node bin/cli`

because : `npm install -g` fails

```
joystream@localhost:~/storage-node-joystream$ npm install -g
npm WARN enoent ENOENT: no such file or directory, open '/home/joystream/storage-node-joystream/lib/joystream/package.json'

npm ERR! path /home/joystream/storage-node-joystream/lib/joystream/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/joystream/storage-node-joystream/lib/joystream/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by jfinkhaeuser** [comment]
Ok, how you run it is not an issue... weird.

Out of curiosity, is this through the proxy or not? If yes, does it work from the machine to the node instance?

**Comment by mnaamani** [comment]
I tried to bypass proxy and get same result. But it looks like I may have been running from an old commit for some reason. Pulling from master and will try again.

**Comment by mnaamani** [comment]
Doing GET directly to port 3000, no proxies..

`wget http://storage-node-1.joystream.org:3000/asset/v0/d084fcd9-c489-57ff-9816-9917aaec0e1e/ef9818a5b76c-4989-b347-31128ebba?download`

Resolving storage-node-1.joystream.org (storage-node-1.joystream.org)... 80.85.86.213
Connecting to storage-node-1.joystream.org (storage-node-1.joystream.org)|80.85.86.213|:3000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 74063411 (71M) [application/octet-stream]
Saving to: 'ef9818a5b76c-4989-b347-31128ebba?download'

ef9818a5b76c-4989-b347-31128ebba?download              0%[                                                                                                                       ]   4.00K  --.-KB/s    in 0s      

2019-04-14 17:49:36 (14.7 MB/s) - Connection closed at byte 4096. Retrying.

**Comment by mnaamani** [comment]
From same host machine:
```
wget http://localhost:3000/asset/v0/d084fcd9-c489-57ff-9816-9917aaec0e1e/ef9818a5b76c-4989-b347-31128ebba?download
--2019-04-14 14:52:28--  http://localhost:3000/asset/v0/d084fcd9-c489-57ff-9816-9917aaec0e1e/ef9818a5b76c-4989-b347-31128ebba?download
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:3000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 74063411 (71M) [application/octet-stream]
Saving to: ‘ef9818a5b76c-4989-b347-31128ebba?download’

ef9818a5b76c-4989-b347-31128ebba?download   0%[                                                                                     ]   4.00K  --.-KB/s    in 0s      

2019-04-14 14:52:28 (174 MB/s) - Connection closed at byte 4096. Retrying.

--2019-04-14 14:52:29--  (try: 2)  http://localhost:3000/asset/v0/d084fcd9-c489-57ff-9816-9917aaec0e1e/ef9818a5b76c-4989-b347-31128ebba?download
Connecting to localhost (localhost)|::1|:3000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:3000... failed: Connection refused.
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:3000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:3000... failed: Connection refused.
```

**Comment by jfinkhaeuser** [comment]
That's so weird. Alright, I'll take a look in a short while.

**Comment by jfinkhaeuser** [comment]
So far, I've been unable to reproduce :-/
