### ISSUE TITLE
During uploading: ReferenceError: api is not defined

### ISSUE THREAD

**Issue by mnaamani** [Joystream/storage-node-joystream#40]
```
```
  joystream:util:ranges = Got chunk with byte range [ 44359608, 44366447 ] +20ms
  joystream:util:ranges Current requested range is [ 0, 48770610 ] +1ms
  joystream:util:ranges Segment to send within chunk is [ 44359608, 44366447 ] +0ms
  joystream:util:ranges Offsets into buffer are [ 0, 6839 ] with length 6840 +0ms
  joystream:util:ranges Chunk is finished, but the requested range is missing bytes. +0ms
ReferenceError: api is not defined
    at PassThrough.ft_stream.on (/home/joystream/storage-node-joystream/paths/asset/v0/{id}/{name}.js:141:27)
    at PassThrough.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
buffer.js:79
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (buffer.js:79:1)
    at Function.alloc (buffer.js:283:10)
    at new Buffer (buffer.js:180:19)
    at increaseBufferIfNecessary (/home/joystream/storage-node-joystream/node_modules/stream-buffers/lib/readable_streambuffer.js:75:23)
    at module.exports.put (/home/joystream/storage-node-joystream/node_modules/stream-buffers/lib/readable_streambuffer.js:93:7)
    at Class.stream.on (/home/joystream/storage-node-joystream/lib/joystream/core/repository.js:202:23)
    at Class.emit (events.js:189:13)
    at addChunk (/home/joystream/storage-node-joystream/node_modules/readable-stream/lib/_stream_readable.js:291:12)
```

**Comment by jfinkhaeuser** [comment]
Fixed in #41 - presumably :)
