### ISSUE TITLE
Getting error on js_storage create

### ISSUE THREAD

**Issue by finnyfound** [Joystream/storage-node-joystream#47]
if `js_storage create` is run and we have created a folder named `storage ` in the default folder (`storage-node-joystream`) before, this error occurs.

```
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir '/home/joy/storage-node-joystream/storage/keys'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Storage._initialize (/home/joy/storage-node-joystream/lib/joystream/core/storage.js:207:8)
    at new Storage (/home/joy/storage-node-joystream/lib/joystream/core/storage.js:52:20)
    at get_storage (/home/joy/storage-node-joystream/bin/cli.js:223:17)
    at Object.create (/home/joy/storage-node-joystream/bin/cli.js:372:19)
    at Object.<anonymous> (/home/joy/storage-node-joystream/bin/cli.js:418:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

```

**Comment by bwhm** [comment]
Hey,
As shown in the output:

> `Error: EEXIST: file already exists, mkdir '/home/joy/storage-node-joystream/storage/keys'`

The storage folder you chose is already created. You can delete if and `js_storage create` for default (as in your case), or set a new one with `js_storage create --storage=/path/to/preferred_storage/directory`.
