### ISSUE TITLE
Error with signup & json launch: "ret.catch(...).finally is not a function"

### ISSUE THREAD

**Issue by sjsqd** [Joystream/storage-node-joystream#50]
I'm using Debian and another user from Telegram who is using Ubuntu have both faced this issue when trying to use the signup command + json file.

```
abc@abc:~/storage-node-joystream$ js_storage signup 5FnXBH.json
/home/abc/storage-node-joystream/bin/cli.js:412
    ret.catch(console.error).finally(_ => process.exit());
                                    ^

TypeError: ret.catch(...).finally is not a function
    at Object.signup (/home/abc/storage-node-joystream/bin/cli.js:412:37)
    at Object.<anonymous> (/home/abc/storage-node-joystream/bin/cli.js:418:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by sjsqd** [comment]
This issue was fixed by updating nodejs version using NPM (I upgraded from 8.16.0 to 10.15.3)
A straightforward tutorial can be found here: https://tecadmin.net/upgrade-nodejs-via-npm/
