### ISSUE TITLE
Error: Cannot find module 'joystream/core/repository' - running tests

### ISSUE THREAD

**Issue by mnaamani** [Joystream/storage-node-joystream#52]
Not able to run tests:

```
MokoBook:storage-node-joystream mokhtar$ npm run test

> joystream-storage@0.1.0 test /Users/mokhtar/joystream/storage-node-joystream
> mocha test/**/*.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'joystream/core/repository'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/mokhtar/joystream/storage-node-joystream/test/core/repository.js:25:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/mokhtar/joystream/storage-node-joystream/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/mokhtar/joystream/storage-node-joystream/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/mokhtar/joystream/storage-node-joystream/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/mokhtar/joystream/storage-node-joystream/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! joystream-storage@0.1.0 test: `mocha test/**/*.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the joystream-storage@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mokhtar/.npm/_logs/2019-04-22T07_17_40_374Z-debug.log
```

**Comment by jfinkhaeuser** [comment]
```
$ yarn build
$ yarn run test
```

I never tried with npm. But the error definitely comes from not running `yarn build`, and is related to #45 .

**Comment by mnaamani** [comment]
confirmed, running `yarn build` before `yarn run test` solved it
