### ISSUE TITLE
Failed to build node-sodium: Cannot find module 'inflight'

### ISSUE THREAD

**Issue by siman** [Joystream/storage-node-joystream#59]
```terminal
Alexs-Air:storage-node-joystream$ yarn run build
yarn run v1.13.0
$ ./build.sh
[1/4] 🔍  Resolving packages...
warning rpc-websockets > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[7/7] ⠄ nodemon
[-/7] ⠄ waiting...
[-/7] ⡀ waiting...
[-/7] ⡀ waiting...
error /Users/alex/storage-node-joystream/node_modules/sodium: Command failed.
Exit code: 1
Command: node install.js --install
Arguments: 
Directory: /Users/alex/storage-node-joystream/node_modules/sodium
Output:
echo Build node-sodium module
Build node-sodium module
node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.4.0 | darwin | x64
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'inflight'
gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:659:17)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:22:18)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:58:16)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:723:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:620:32)
gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alex/storage-node-joystream/node_modules/sodium
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
make: *** [nodesodium] Error 7
/Users/alex/storage-node-joystream/node_modules/sodium/install.js:293
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code 2


$ /Users/alex/storage-node-joystream/node_modules/.bin/tsc --build tsconfig.json
✨  Done in 226.87s.

```

**Comment by jfinkhaeuser** [comment]
I suspect that's a Darwin thing. I've never even heard of `inflight`.

It is in my `node_modules`, though, and it's pure JS.

**Comment by siman** [comment]
My environment is: Mac + Node v11.4.0 + latest storage-node

**Comment by jfinkhaeuser** [comment]
Right, and I've been building on v10. I'll create a quick PR to enforce that, and then I can try upgrading later. I suspect that's the issue we're seeing.

**Comment by jfinkhaeuser** [comment]
Builds with v11.14.0 for me, though, so this might not be the issue.

**Comment by siman** [comment]
**Update**: Now storage node works for me.

I had a broken npm for some reason, so I installed the latest one and now I can build and run a storage node.
